### PR TITLE
feat: Packaging mrf dkms as a deb package

### PR DESCRIPTION
**Pull request by gabrielfedel**
This is a PR of the the debian packaging for mrf dkms, and it is my first debian package so sorry if there is something too unconventional.

With this PR it is possible to build a .deb package that works for Debian (tested on 10) and Ubuntu (tested on 22.04).

Some important points:

* I chose to not use the information available on CONFIG (as it is used by rpm) as for debian package we have to keep the changelog file, so sounded better to not have any automatic filling. That means that the debian package should be updated when there are new kernel driver releases. 
* Regarding the version, I chose to use the defined version (3) and the way debian version the packages, resulting in the first version as 3-0.
* The package name is mrf-dkms, as the module is loaded as mrf. That looks the right choice as it seems was the used one on other similar works to have it as a debian package
* The list of authors was got using `git shortlog -sne ./mrmShared/linux` and removing duplicated names

### CODE REVIEW

**Comment by gabrielfedel** [comment]
I'm trying to rename the package to mrfioc2-dkms, but this make the installation process attached to that name and it looks for a mrfioc2.ko (it might be ways to work around that but I'm not finding them) . Any suggestions on how to proceed ? Move the driver to mrfioc2 ? or keep the package as mrf-dkms ? Or a third option ?

**Comment by jerzyjamroz** [comment]
I changed the .rpm accordingly: https://github.com/epics-modules/mrfioc2/pull/129
If there is another preference then comments are welcome. It would be good to keep the consistency across different package types.

**Comment by jerzyjamroz** [comment]
@lucmaga , support the review.

**Comment by gabrielfedel** [comment]
Ok, the package is ready to be reviewed.

**Comment by lucmaga** [comment]
Tested on Ubuntu also, works as expected.
Only thing I would add, maybe it does not fit in this PR, is to automatically do it using CI for the releases.

Anyway, LGTM.

**Pull request merged**
