### PR TITLE
Complete MTCA EVR300U substitution file 

### PR DESCRIPTION
**Pull request by agaget**
It adds function set and reset, planned in the substitutions files. 
It also adds missing inputs : The four possible universal inputs and the 8 backplane inputs.

This version has been tested in labo and another version of mrfioc2 with similar modifications has been used in production since 3 years.

### CODE REVIEW

**Comment by jerzyjamroz** [comment]
@zioven , if no objections then I will merge this soon. Let me know your opinion.

**Comment by agaget** [comment]
> @zioven , if no objections then I will merge this soon. Let me know your opinion.

If it's ok for you, I can add it to the new universal subsitutions also

**Comment by jerzyjamroz** [comment]
> > @zioven , if no objections then I will merge this soon. Let me know your opinion.
> 
> If it's ok for you, I can add it to the new universal subsitutions also

Sure.

**Comment by zioven** [comment]
looks OK to me

**Pull request merged**
