### PR TITLE
feat: dedup and simplify sequencer db.

### PR DESCRIPTION
**Pull request by jerzyjamroz**
split out common of evr/evg (everything except trig source select) apply string LUT to readbacks

### CODE REVIEW

**Comment by jerzyjamroz** [comment]
The original commit: ```https://github.com/icshwi/mrfioc2/blame/162e6041655c6b0f88c23d3b754cf22b5db52bb9/evgMrmApp/Db/evgSoftSeq.template```

**Comment by zioven** [comment]
Is there a reason why the additional UNIV options are getting removed?

As far as I have discussed with Jukka, the mTCA EVM can still have an RTM and option for additional 5 UNIV-IO input modules up there ...

Also, how does this map with s VME version of the EVM-300 series?

**Comment by jerzyjamroz** [comment]
@zioven, I am not an author of this patch but it seems you are right. We have been using this patch but not all the configurations (and only MTCA), so the part related to Univ3..15 might need to be reapplied to this PR (as you noticed).

**Comment by jerzyjamroz** [comment]
@mdavidsaver , I consider it as obsolete, until you manage this PR differently.

**Comment by mdavidsaver** [comment]
What I believe is the original version of this patch was applied as 162e6041655c6b0f88c23d3b754cf22b5db52bb9.

Part of this change was the `LUT uint32 -> string` device support to work around the limited number of states supported by the mbbi record.  Since having a list of enumerations is less important for a readback, I thought having one stringin record with a Look Up Table encoded in `info()` tags was preferable to having several `mbbi` records, with only one showing a valid selection at any one time.

**Pull request closed without merging**
