### PR TITLE
convert opi to bob with new naming, harmonized with a color.def 

### PR DESCRIPTION
**Pull request by agaget**
This is the old opis converted in bob and improved a little and with new MACROS for the color. I have put the color.def I have used for those bobs . I've tried to be as close as possible to the already existing macro and to the example furnished with phoebus.(https://github.com/ControlSystemStudio/phoebus/blob/master/app/display/model/src/main/resources/examples/color.def)

I've added a directory bob directly in the top. I thinkthat the old architecture where opis was lost in the different App is a little bit confusing...

mrfioc2/bob
├── color.def
├── evg
│   ├── _evginput.bob....
│   ├── .... etc..
├── evr
│   ├── evr-cml-output.bob
│   ├── ... etc
└── launcher.bob

I also can do something like that to let room to @gabrielfedel proposition he mentionned earlier

mrfioc2/bob
bob
├── standard
│   ├── color.def
│   ├── evg
│   │   ├── _evginput.bob
│   │   ├── etc ...
│   ├── evr
│   │   ├── evr-cml-output.bob
│   │   ├── etc...
│   └── launcher.bob
├── essBob
│   ├──etc ...

What do you think @jerzyjamroz @gabrielfedel  @mdavidsaver ?

### CODE REVIEW

**Comment by jerzyjamroz** [comment]
@agaget , thanks for the contributions. I think it might be better to change ```bob``` directory to ```phoebus``` as those files are tool-dependent.

**Comment by prjemian** [comment]
Please keep the directory name as `bob`, to be consistent with other EPICS modules.

**Comment by agaget** [comment]
> Please keep the directory name as `bob`, to be consistent with other EPICS modules.

I agree with the trombonist ;)

I was looking at it in different community modules and even if the word consistency can be a little bit strong, it seems to usually used the name of the format. 

https://github.com/epics-modules/asyn/tree/master/opi
in ayn this is the opi directory when you find medm, bob etc ... 😐 

https://github.com/epics-modules/modbus/tree/master/modbusApp/op
A lot of them have the directory op (don't know the meaning) the put the graphical files in it. Maybe we can do something like that ...

Moreover the bob file can be used for example with the dbwr (https://github.com/ornl-epics/dbwr)

**Comment by gabrielfedel** [comment]
Nice work @agaget .

I dig a bit into the bob files and found some issues:
* Missing embedded displays for EVRU and EVRD (on both EVMs)
* Missing displays for sequencers for EVRs
* Some parts that shouldn't exist for PCIe (like backplane configuration). For this one specifically I can maybe fix as we do have this hardware and would be easier for me to test. If you prefer we could approve the PCIe as it is and later I open a new MR to fix it.

Besides these, regarding the folder organization my suggestion would be to have 

mrfioc2/opi/bob/

Than later if fits the ess ones I will probably suggest another level of folder.

I'm also thinking that we should move the existent opi files to that new folder, but this probably should be in a new MR.

**Comment by jerzyjamroz** [comment]
```opi``` (Operator Interface) is the generic name, after your comments it looks like the way to go. ```op``` probably means ```Operator``` "space", so it might include more (or not) than interface related.

**Comment by agaget** [comment]
>     * Missing embedded displays for EVRU and EVRD (on both EVMs)
I will correct it, I have been a little bit too fast when I decided to split in 2 directories (evr/evg) and didn't make enough test apparently.
>     * Missing displays for sequencers for EVRs
Ok
>     * Some parts that shouldn't exist for PCIe (like backplane configuration). For this one specifically I can maybe fix as we do have this hardware and would be easier for me to test. If you prefer we could approve the PCIe as it is and later I open a new MR to fix it.

We have one, but not configured completely to our new environment so quite complicated to test right away. If you can modify it it would be nice ! (Moreover I was not aware of a backplane configuration for the PCIe)

> Besides these, regarding the folder organization my suggestion would be to have
> 
> mrfioc2/opi/bob/
> 
> Than later if fits the ess ones I will probably suggest another level of folder.

> opi (Operator Interface) is the generic name, after your comments it looks like the way to go
Fine for me, i change to that.

> I'm also thinking that we should move the existent opi files to that new folder, but this probably should be in a new MR.

I agree, but the old OPIs for now respect the old PV naming convention, the old color and the old architecture, it's a whole new work. Maybe I should have work on the OPI and convert them to Bob, but it's not what I have done so the Opis are untouched on my side. A futur MR for sure

**Comment by agaget** [comment]
I corrected the issue you pointed out @gabrielfedel (i hope everything) in fact the PCIe was not linked to the correct bob, so it should be better and without Backplane but univ instead. I still didn't be able to tested it with real PVs.

And I apply `opi/bob/*.bob`

**Comment by gabrielfedel** [comment]
Nice @agaget ! I just found some small issues with the PCIe that I fixed by myself (Front Panel input prefixes, one wrong active table, and one wrong number for Front Panel input). Please let me know if it looks ok for you.

**Review by gabrielfedel — APPROVED** [review]
LGTM!

**Comment by agaget** [comment]
> Nice @agaget ! I just found some small issues with the PCIe that I fixed by myself (Front Panel input prefixes, one wrong active table, and one wrong number for Front Panel input). Please let me know if it looks ok for you.

LGTM :) 
(I've just learn this accronym thanks to you)

**Review by jerzyjamroz — APPROVED** [review]

**Pull request merged**
