### PR TITLE
Add featuring masks/enable

### PR DESCRIPTION
**Pull request by agaget**
This PR add mask (and enable) functionalities for the sequencer. See chapter **2.4 Event Sequence**r (of the 2021 manual maybe it's updated now)

image

It add possibility of the sofware mask/enable (register SQSWMASK and SQSWENA) and mask attached to physical input. See register FP0SQMK and FP0SQEEN.

I've added and iocseqmask to have an example. It works with an MTCA EVM300 and MTCA EVR300U, using backplanes as physical input and output.

For SARAF MPS we are using the mask functionnality to stop producing the chopper pulse, stop the magnetron, but not stopping RF, so we are masking events of the sequence without stopping the sequencer.

### CODE REVIEW

**Comment by agaget** [comment]
> @agaget , thanks for this feature. Could you rebase it to the master branch?

It should be ok now. 
I have tested again the ioc to check no regression, it works fine

**Comment by agaget** [comment]
One more thing if it's possible after the PR to increment the tag number please ? Not necessary major version-> 2.5.1
Except if you already plan to increment it soon
Thanks

**Comment by jerzyjamroz** [comment]
@agaget , I did an initial review and your work looks well thought out and tested. 
On the other hand, I will need more time to go deep into it to give you feedback (I am busy at this moment), and I do not want to block you. It means I will merge it now and if any feedback appears, I will propose a PR for your review, and then it will get the tag.

One comment:
```
#Can't dbpf waveform of UCHAR so we use this. Change architecture if needed.
```
I think you can contribute to the ```dbpf``` tool to have the capability to write digits to it. It would be useful for the whole community.

**Comment by agaget** [comment]
> @agaget , I did an initial review and your work looks well thought out and tested. On the other hand, I will need more time to go deep into it to give you feedback (I am busy at this moment), and I do not want to block you. It means I will merge it now and if any feedback appears, I will propose a PR for your review, and then it will get the tag.

I'm glad that it's merged now and I'm fine with your proposition

> I think you can contribute to the `dbpf` tool to have the capability to write digits to it. It would be useful for the whole community.

I agree and I'd like to look at it, unfortunately like you I'm quite busy lately and it's not going better..

Thanks

**Comment by agaget** [comment]
And is it possible to tag to 2.5.1 please ?

**Comment by jerzyjamroz** [comment]
It is 2.6 already as there are other things included in regards to 2.5. I will mark it but without making the release.

**Comment by agaget** [comment]
> It is 2.6 already as there are other things included in regards to 2.5. I will mark it but without making the release.
Ok perfect, no need for 2.5.1 if this is in 2.6. The tag just appear for me I wasn't able to see it before.

**Pull request merged**
